work_group: ${PRIMUS_TEAM:local}
user_name: ${PRIMUS_USER:local}
exp_name: ${PRIMUS_EXP_NAME:flux.1_schnell_t2i-raw-pretrain}
workspace: ${PRIMUS_WORKSPACE:./output}

platform:
  config: platform_local.yaml

modules:
  pre_trainer:
    framework: diffusion
    config: pre_trainer.yaml

    model: flux.1_schnell_t2i.yaml
    overrides:
      sink_level: null
      file_sink_level: INFO
      stderr_sink_level: INFO

      model:
        config:
          encoder:
            t5_encoder: ${T5_ENCODER:google/t5-v1_1-xxl}
            clip_encoder: ${CLIP_ENCODER:openai/clip-vit-large-patch14}
            autoencoder: ${VAE_CHECKPOINT:black-forest-labs/FLUX.1-dev/ae.safetensors}
            max_t5_length: ${MAX_T5_LENGTH:256}

      metrics:
        log_freq: 1
        enable_wandb: false

      training:
        local_batch_size: ${LOCAL_BATCH_SIZE:1}
        steps: ${MAX_STEPS:50}
        num_train_epochs: 1000
        gradient_accumulation_steps: 1
        output_dir: ${OUTPUT_DIR:./output/flux.1_schnell_t2i-raw-pretrain}
        save_steps: 0
        save_strategy: ${SAVE_STRATEGY:dit_only}
        run_name: flux.1_schnell_t2i-raw-pretrain

      data:
        dataset_type: raw
        dataset: ${DATASET:cc12m-test}
        dataset_format: ${DATASET_FORMAT:webdataset}
        dataset_path: ${DATASET_PATH:}
        prompt_dropout_prob: ${PROMPT_DROPOUT_PROB:0.1}
        img_size: ${IMG_SIZE:256}
        skip_low_resolution: false

      parallelism:
        sp_size: 1
        dp_replicate: ${DP_REPLICATE:1}

      optimizer:
        lr: ${LR:2.0e-4}
        weight_decay: ${WEIGHT_DECAY:0.1}
        adam_beta2: ${ADAM_BETA2:0.95}

      lr_scheduler:
        lr_scheduler_type: constant_with_warmup
        warmup_steps: ${WARMUP_STEPS:1600}

      runtime:
        attention_backend: ${ATTENTION_BACKEND:flash_attn_aiter}
        gradient_checkpointing: ${GRADIENT_CHECKPOINTING:false}
        compile_transformer_blocks: ${COMPILE_TRANSFORMER_BLOCKS:true}
        fsdp2_reshard_after_forward: ${FSDP2_RESHARD_AFTER_FORWARD:true}
        report_to: none
